Traceback (most recent call last):
  File "pb_price_reversal.py", line 12, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
Traceback (most recent call last):
  File "pb_price_reversal.py", line 12, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
